/// Flutter icons ScanCustomIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ScanCustomIcon
///      fonts:
///       - asset: fonts/ScanCustomIcon.ttf
///
///
///
// ignore_for_file: constant_identifier_names
library;

import 'package:flutter/widgets.dart';

class ScanCustomIcon {
  ScanCustomIcon._();

  static const _kFontFam = 'ScanCustomIcon';
  static const String? _kFontPkg = null;

  static const IconData scanIcon = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
